# Generated by Django 5.2.10 on 2026-01-27 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["-updated_at"], name="chat_chatse_updated_96b812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_chatse_user_id_40a24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["session", "-uploaded_at"],
                name="chat_docume_session_f84116_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_4940cf_idx"
            ),
        ),
    ]
