# Generated by Django 5.2.10 on 2026-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatsession_options_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="model_used",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
